/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.21.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.tetrate.tsb.gateway.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.tetrate.tsb.gateway.models.V2IngressGatewaySpecRoutingCorsPolicy;
import io.tetrate.tsb.gateway.models.V2IngressGatewaySpecRoutingRules;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * Routing rules associated with HTTP traffic to this service.
 */
@ApiModel(description = "Routing rules associated with HTTP traffic to this service.")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-12-20T22:11:16.316Z[Etc/UTC]")
public class V2IngressGatewaySpecRouting {
  public static final String SERIALIZED_NAME_CORS_POLICY = "corsPolicy";
  @SerializedName(SERIALIZED_NAME_CORS_POLICY)
  private V2IngressGatewaySpecRoutingCorsPolicy corsPolicy;

  public static final String SERIALIZED_NAME_RULES = "rules";
  @SerializedName(SERIALIZED_NAME_RULES)
  private List<V2IngressGatewaySpecRoutingRules> rules = null;


  public V2IngressGatewaySpecRouting corsPolicy(V2IngressGatewaySpecRoutingCorsPolicy corsPolicy) {
    
    this.corsPolicy = corsPolicy;
    return this;
  }

   /**
   * Get corsPolicy
   * @return corsPolicy
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public V2IngressGatewaySpecRoutingCorsPolicy getCorsPolicy() {
    return corsPolicy;
  }


  public void setCorsPolicy(V2IngressGatewaySpecRoutingCorsPolicy corsPolicy) {
    this.corsPolicy = corsPolicy;
  }


  public V2IngressGatewaySpecRouting rules(List<V2IngressGatewaySpecRoutingRules> rules) {
    
    this.rules = rules;
    return this;
  }

  public V2IngressGatewaySpecRouting addRulesItem(V2IngressGatewaySpecRoutingRules rulesItem) {
    if (this.rules == null) {
      this.rules = new ArrayList<>();
    }
    this.rules.add(rulesItem);
    return this;
  }

   /**
   * HTTP routes.
   * @return rules
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "HTTP routes.")

  public List<V2IngressGatewaySpecRoutingRules> getRules() {
    return rules;
  }


  public void setRules(List<V2IngressGatewaySpecRoutingRules> rules) {
    this.rules = rules;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V2IngressGatewaySpecRouting v2IngressGatewaySpecRouting = (V2IngressGatewaySpecRouting) o;
    return Objects.equals(this.corsPolicy, v2IngressGatewaySpecRouting.corsPolicy) &&
        Objects.equals(this.rules, v2IngressGatewaySpecRouting.rules);
  }

  @Override
  public int hashCode() {
    return Objects.hash(corsPolicy, rules);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V2IngressGatewaySpecRouting {\n");
    sb.append("    corsPolicy: ").append(toIndentedString(corsPolicy)).append("\n");
    sb.append("    rules: ").append(toIndentedString(rules)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

