/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.21.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.tetrate.tsb.gateway.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * V2IngressGatewaySpecTlsFiles
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-12-20T22:11:16.316Z[Etc/UTC]")
public class V2IngressGatewaySpecTlsFiles {
  public static final String SERIALIZED_NAME_CA_CERTIFICATES = "caCertificates";
  @SerializedName(SERIALIZED_NAME_CA_CERTIFICATES)
  private String caCertificates;

  public static final String SERIALIZED_NAME_PRIVATE_KEY = "privateKey";
  @SerializedName(SERIALIZED_NAME_PRIVATE_KEY)
  private String privateKey;

  public static final String SERIALIZED_NAME_SERVER_CERTIFICATE = "serverCertificate";
  @SerializedName(SERIALIZED_NAME_SERVER_CERTIFICATE)
  private String serverCertificate;


  public V2IngressGatewaySpecTlsFiles caCertificates(String caCertificates) {
    
    this.caCertificates = caCertificates;
    return this;
  }

   /**
   * Get caCertificates
   * @return caCertificates
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getCaCertificates() {
    return caCertificates;
  }


  public void setCaCertificates(String caCertificates) {
    this.caCertificates = caCertificates;
  }


  public V2IngressGatewaySpecTlsFiles privateKey(String privateKey) {
    
    this.privateKey = privateKey;
    return this;
  }

   /**
   * Get privateKey
   * @return privateKey
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getPrivateKey() {
    return privateKey;
  }


  public void setPrivateKey(String privateKey) {
    this.privateKey = privateKey;
  }


  public V2IngressGatewaySpecTlsFiles serverCertificate(String serverCertificate) {
    
    this.serverCertificate = serverCertificate;
    return this;
  }

   /**
   * Get serverCertificate
   * @return serverCertificate
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getServerCertificate() {
    return serverCertificate;
  }


  public void setServerCertificate(String serverCertificate) {
    this.serverCertificate = serverCertificate;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V2IngressGatewaySpecTlsFiles v2IngressGatewaySpecTlsFiles = (V2IngressGatewaySpecTlsFiles) o;
    return Objects.equals(this.caCertificates, v2IngressGatewaySpecTlsFiles.caCertificates) &&
        Objects.equals(this.privateKey, v2IngressGatewaySpecTlsFiles.privateKey) &&
        Objects.equals(this.serverCertificate, v2IngressGatewaySpecTlsFiles.serverCertificate);
  }

  @Override
  public int hashCode() {
    return Objects.hash(caCertificates, privateKey, serverCertificate);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V2IngressGatewaySpecTlsFiles {\n");
    sb.append("    caCertificates: ").append(toIndentedString(caCertificates)).append("\n");
    sb.append("    privateKey: ").append(toIndentedString(privateKey)).append("\n");
    sb.append("    serverCertificate: ").append(toIndentedString(serverCertificate)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

