/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.21.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.tetrate.tsb.gateway.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.tetrate.tsb.gateway.models.V2IngressGatewaySpecRoutingModifyHeadersRequest;
import io.tetrate.tsb.gateway.models.V2IngressGatewaySpecRoutingModifyHeadersResponse;
import java.io.IOException;

/**
 * Add/remove/overwrite one or more HTTP headers in a request or response.
 */
@ApiModel(description = "Add/remove/overwrite one or more HTTP headers in a request or response.")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-12-20T22:11:16.316Z[Etc/UTC]")
public class V2IngressGatewaySpecRoutingModifyHeaders {
  public static final String SERIALIZED_NAME_REQUEST = "request";
  @SerializedName(SERIALIZED_NAME_REQUEST)
  private V2IngressGatewaySpecRoutingModifyHeadersRequest request;

  public static final String SERIALIZED_NAME_RESPONSE = "response";
  @SerializedName(SERIALIZED_NAME_RESPONSE)
  private V2IngressGatewaySpecRoutingModifyHeadersResponse response;


  public V2IngressGatewaySpecRoutingModifyHeaders request(V2IngressGatewaySpecRoutingModifyHeadersRequest request) {
    
    this.request = request;
    return this;
  }

   /**
   * Get request
   * @return request
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public V2IngressGatewaySpecRoutingModifyHeadersRequest getRequest() {
    return request;
  }


  public void setRequest(V2IngressGatewaySpecRoutingModifyHeadersRequest request) {
    this.request = request;
  }


  public V2IngressGatewaySpecRoutingModifyHeaders response(V2IngressGatewaySpecRoutingModifyHeadersResponse response) {
    
    this.response = response;
    return this;
  }

   /**
   * Get response
   * @return response
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public V2IngressGatewaySpecRoutingModifyHeadersResponse getResponse() {
    return response;
  }


  public void setResponse(V2IngressGatewaySpecRoutingModifyHeadersResponse response) {
    this.response = response;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V2IngressGatewaySpecRoutingModifyHeaders v2IngressGatewaySpecRoutingModifyHeaders = (V2IngressGatewaySpecRoutingModifyHeaders) o;
    return Objects.equals(this.request, v2IngressGatewaySpecRoutingModifyHeaders.request) &&
        Objects.equals(this.response, v2IngressGatewaySpecRoutingModifyHeaders.response);
  }

  @Override
  public int hashCode() {
    return Objects.hash(request, response);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V2IngressGatewaySpecRoutingModifyHeaders {\n");
    sb.append("    request: ").append(toIndentedString(request)).append("\n");
    sb.append("    response: ").append(toIndentedString(response)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

