/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.21.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.tetrate.tsb.gateway.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.tetrate.tsb.gateway.models.V2IngressGatewaySpecRateLimitingExternalServiceHeaderValueMatchHeaders;
import java.io.IOException;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * Rate limit on the existence of certain request headers.
 */
@ApiModel(description = "Rate limit on the existence of certain request headers.")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-12-20T22:11:16.316Z[Etc/UTC]")
public class V2IngressGatewaySpecRateLimitingExternalServiceHeaderValueMatch {
  public static final String SERIALIZED_NAME_DESCRIPTOR_VALUE = "descriptorValue";
  @SerializedName(SERIALIZED_NAME_DESCRIPTOR_VALUE)
  private String descriptorValue;

  public static final String SERIALIZED_NAME_HEADERS = "headers";
  @SerializedName(SERIALIZED_NAME_HEADERS)
  private Map<String, V2IngressGatewaySpecRateLimitingExternalServiceHeaderValueMatchHeaders> headers = null;


  public V2IngressGatewaySpecRateLimitingExternalServiceHeaderValueMatch descriptorValue(String descriptorValue) {
    
    this.descriptorValue = descriptorValue;
    return this;
  }

   /**
   * The value to use in the descriptor entry.
   * @return descriptorValue
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The value to use in the descriptor entry.")

  public String getDescriptorValue() {
    return descriptorValue;
  }


  public void setDescriptorValue(String descriptorValue) {
    this.descriptorValue = descriptorValue;
  }


  public V2IngressGatewaySpecRateLimitingExternalServiceHeaderValueMatch headers(Map<String, V2IngressGatewaySpecRateLimitingExternalServiceHeaderValueMatchHeaders> headers) {
    
    this.headers = headers;
    return this;
  }

  public V2IngressGatewaySpecRateLimitingExternalServiceHeaderValueMatch putHeadersItem(String key, V2IngressGatewaySpecRateLimitingExternalServiceHeaderValueMatchHeaders headersItem) {
    if (this.headers == null) {
      this.headers = new HashMap<>();
    }
    this.headers.put(key, headersItem);
    return this;
  }

   /**
   * Get headers
   * @return headers
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Map<String, V2IngressGatewaySpecRateLimitingExternalServiceHeaderValueMatchHeaders> getHeaders() {
    return headers;
  }


  public void setHeaders(Map<String, V2IngressGatewaySpecRateLimitingExternalServiceHeaderValueMatchHeaders> headers) {
    this.headers = headers;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V2IngressGatewaySpecRateLimitingExternalServiceHeaderValueMatch v2IngressGatewaySpecRateLimitingExternalServiceHeaderValueMatch = (V2IngressGatewaySpecRateLimitingExternalServiceHeaderValueMatch) o;
    return Objects.equals(this.descriptorValue, v2IngressGatewaySpecRateLimitingExternalServiceHeaderValueMatch.descriptorValue) &&
        Objects.equals(this.headers, v2IngressGatewaySpecRateLimitingExternalServiceHeaderValueMatch.headers);
  }

  @Override
  public int hashCode() {
    return Objects.hash(descriptorValue, headers);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V2IngressGatewaySpecRateLimitingExternalServiceHeaderValueMatch {\n");
    sb.append("    descriptorValue: ").append(toIndentedString(descriptorValue)).append("\n");
    sb.append("    headers: ").append(toIndentedString(headers)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

