/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.21.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.tetrate.tsb.gateway.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.tetrate.tsb.gateway.models.V2IngressGatewaySpecRateLimitingSettingsRules;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * V2IngressGatewaySpecRateLimitingSettings
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-12-20T22:11:16.316Z[Etc/UTC]")
public class V2IngressGatewaySpecRateLimitingSettings {
  public static final String SERIALIZED_NAME_FAIL_CLOSED = "failClosed";
  @SerializedName(SERIALIZED_NAME_FAIL_CLOSED)
  private Boolean failClosed;

  public static final String SERIALIZED_NAME_RULES = "rules";
  @SerializedName(SERIALIZED_NAME_RULES)
  private List<V2IngressGatewaySpecRateLimitingSettingsRules> rules = null;

  public static final String SERIALIZED_NAME_TIMEOUT = "timeout";
  @SerializedName(SERIALIZED_NAME_TIMEOUT)
  private String timeout;


  public V2IngressGatewaySpecRateLimitingSettings failClosed(Boolean failClosed) {
    
    this.failClosed = failClosed;
    return this;
  }

   /**
   * Get failClosed
   * @return failClosed
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Boolean getFailClosed() {
    return failClosed;
  }


  public void setFailClosed(Boolean failClosed) {
    this.failClosed = failClosed;
  }


  public V2IngressGatewaySpecRateLimitingSettings rules(List<V2IngressGatewaySpecRateLimitingSettingsRules> rules) {
    
    this.rules = rules;
    return this;
  }

  public V2IngressGatewaySpecRateLimitingSettings addRulesItem(V2IngressGatewaySpecRateLimitingSettingsRules rulesItem) {
    if (this.rules == null) {
      this.rules = new ArrayList<>();
    }
    this.rules.add(rulesItem);
    return this;
  }

   /**
   * A list of rules for ratelimiting.
   * @return rules
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "A list of rules for ratelimiting.")

  public List<V2IngressGatewaySpecRateLimitingSettingsRules> getRules() {
    return rules;
  }


  public void setRules(List<V2IngressGatewaySpecRateLimitingSettingsRules> rules) {
    this.rules = rules;
  }


  public V2IngressGatewaySpecRateLimitingSettings timeout(String timeout) {
    
    this.timeout = timeout;
    return this;
  }

   /**
   * The timeout in seconds for the rate limit server RPC.
   * @return timeout
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The timeout in seconds for the rate limit server RPC.")

  public String getTimeout() {
    return timeout;
  }


  public void setTimeout(String timeout) {
    this.timeout = timeout;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V2IngressGatewaySpecRateLimitingSettings v2IngressGatewaySpecRateLimitingSettings = (V2IngressGatewaySpecRateLimitingSettings) o;
    return Objects.equals(this.failClosed, v2IngressGatewaySpecRateLimitingSettings.failClosed) &&
        Objects.equals(this.rules, v2IngressGatewaySpecRateLimitingSettings.rules) &&
        Objects.equals(this.timeout, v2IngressGatewaySpecRateLimitingSettings.timeout);
  }

  @Override
  public int hashCode() {
    return Objects.hash(failClosed, rules, timeout);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V2IngressGatewaySpecRateLimitingSettings {\n");
    sb.append("    failClosed: ").append(toIndentedString(failClosed)).append("\n");
    sb.append("    rules: ").append(toIndentedString(rules)).append("\n");
    sb.append("    timeout: ").append(toIndentedString(timeout)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

