/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.21.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.tetrate.tsb.gateway.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.tetrate.tsb.gateway.models.V2IngressGatewaySpecAuthorizationLocalFrom;
import io.tetrate.tsb.gateway.models.V2IngressGatewaySpecAuthorizationLocalTo;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * V2IngressGatewaySpecAuthorizationLocalRules
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-12-20T22:11:16.316Z[Etc/UTC]")
public class V2IngressGatewaySpecAuthorizationLocalRules {
  public static final String SERIALIZED_NAME_FROM = "from";
  @SerializedName(SERIALIZED_NAME_FROM)
  private List<V2IngressGatewaySpecAuthorizationLocalFrom> from = null;

  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  private String name;

  public static final String SERIALIZED_NAME_TO = "to";
  @SerializedName(SERIALIZED_NAME_TO)
  private List<V2IngressGatewaySpecAuthorizationLocalTo> to = null;


  public V2IngressGatewaySpecAuthorizationLocalRules from(List<V2IngressGatewaySpecAuthorizationLocalFrom> from) {
    
    this.from = from;
    return this;
  }

  public V2IngressGatewaySpecAuthorizationLocalRules addFromItem(V2IngressGatewaySpecAuthorizationLocalFrom fromItem) {
    if (this.from == null) {
      this.from = new ArrayList<>();
    }
    this.from.add(fromItem);
    return this;
  }

   /**
   * Get from
   * @return from
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<V2IngressGatewaySpecAuthorizationLocalFrom> getFrom() {
    return from;
  }


  public void setFrom(List<V2IngressGatewaySpecAuthorizationLocalFrom> from) {
    this.from = from;
  }


  public V2IngressGatewaySpecAuthorizationLocalRules name(String name) {
    
    this.name = name;
    return this;
  }

   /**
   * A friendly name to identify the binding.
   * @return name
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "A friendly name to identify the binding.")

  public String getName() {
    return name;
  }


  public void setName(String name) {
    this.name = name;
  }


  public V2IngressGatewaySpecAuthorizationLocalRules to(List<V2IngressGatewaySpecAuthorizationLocalTo> to) {
    
    this.to = to;
    return this;
  }

  public V2IngressGatewaySpecAuthorizationLocalRules addToItem(V2IngressGatewaySpecAuthorizationLocalTo toItem) {
    if (this.to == null) {
      this.to = new ArrayList<>();
    }
    this.to.add(toItem);
    return this;
  }

   /**
   * Get to
   * @return to
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<V2IngressGatewaySpecAuthorizationLocalTo> getTo() {
    return to;
  }


  public void setTo(List<V2IngressGatewaySpecAuthorizationLocalTo> to) {
    this.to = to;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V2IngressGatewaySpecAuthorizationLocalRules v2IngressGatewaySpecAuthorizationLocalRules = (V2IngressGatewaySpecAuthorizationLocalRules) o;
    return Objects.equals(this.from, v2IngressGatewaySpecAuthorizationLocalRules.from) &&
        Objects.equals(this.name, v2IngressGatewaySpecAuthorizationLocalRules.name) &&
        Objects.equals(this.to, v2IngressGatewaySpecAuthorizationLocalRules.to);
  }

  @Override
  public int hashCode() {
    return Objects.hash(from, name, to);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V2IngressGatewaySpecAuthorizationLocalRules {\n");
    sb.append("    from: ").append(toIndentedString(from)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    to: ").append(toIndentedString(to)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

