/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.21.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.tetrate.tsb.gateway.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * Rewrite the HTTP Host or URL or both.
 */
@ApiModel(description = "Rewrite the HTTP Host or URL or both.")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-12-20T22:11:16.316Z[Etc/UTC]")
public class V2IngressGatewaySpecRoutingModifyRewrite {
  public static final String SERIALIZED_NAME_AUTHORITY = "authority";
  @SerializedName(SERIALIZED_NAME_AUTHORITY)
  private String authority;

  public static final String SERIALIZED_NAME_URI = "uri";
  @SerializedName(SERIALIZED_NAME_URI)
  private String uri;


  public V2IngressGatewaySpecRoutingModifyRewrite authority(String authority) {
    
    this.authority = authority;
    return this;
  }

   /**
   * Rewrite the Authority/Host header with this value.
   * @return authority
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Rewrite the Authority/Host header with this value.")

  public String getAuthority() {
    return authority;
  }


  public void setAuthority(String authority) {
    this.authority = authority;
  }


  public V2IngressGatewaySpecRoutingModifyRewrite uri(String uri) {
    
    this.uri = uri;
    return this;
  }

   /**
   * Rewrite the path (or the prefix) portion of the URI with this value.
   * @return uri
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Rewrite the path (or the prefix) portion of the URI with this value.")

  public String getUri() {
    return uri;
  }


  public void setUri(String uri) {
    this.uri = uri;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V2IngressGatewaySpecRoutingModifyRewrite v2IngressGatewaySpecRoutingModifyRewrite = (V2IngressGatewaySpecRoutingModifyRewrite) o;
    return Objects.equals(this.authority, v2IngressGatewaySpecRoutingModifyRewrite.authority) &&
        Objects.equals(this.uri, v2IngressGatewaySpecRoutingModifyRewrite.uri);
  }

  @Override
  public int hashCode() {
    return Objects.hash(authority, uri);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V2IngressGatewaySpecRoutingModifyRewrite {\n");
    sb.append("    authority: ").append(toIndentedString(authority)).append("\n");
    sb.append("    uri: ").append(toIndentedString(uri)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

