/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.21.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.tetrate.tsb.gateway.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.tetrate.tsb.gateway.models.V2IngressGatewaySpecAuthorizationExternalTlsFiles;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * V2IngressGatewaySpecAuthorizationExternalTls
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-12-20T22:11:16.316Z[Etc/UTC]")
public class V2IngressGatewaySpecAuthorizationExternalTls {
  public static final String SERIALIZED_NAME_FILES = "files";
  @SerializedName(SERIALIZED_NAME_FILES)
  private V2IngressGatewaySpecAuthorizationExternalTlsFiles files;

  /**
   * Gets or Sets mode
   */
  @JsonAdapter(ModeEnum.Adapter.class)
  public enum ModeEnum {
    DISABLED("DISABLED"),
    
    SIMPLE("SIMPLE"),
    
    MUTUAL("MUTUAL");

    private String value;

    ModeEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static ModeEnum fromValue(String value) {
      for (ModeEnum b : ModeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<ModeEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final ModeEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public ModeEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return ModeEnum.fromValue(value);
      }
    }
  }

  public static final String SERIALIZED_NAME_MODE = "mode";
  @SerializedName(SERIALIZED_NAME_MODE)
  private ModeEnum mode;

  public static final String SERIALIZED_NAME_SUBJECT_ALT_NAMES = "subjectAltNames";
  @SerializedName(SERIALIZED_NAME_SUBJECT_ALT_NAMES)
  private List<String> subjectAltNames = null;


  public V2IngressGatewaySpecAuthorizationExternalTls files(V2IngressGatewaySpecAuthorizationExternalTlsFiles files) {
    
    this.files = files;
    return this;
  }

   /**
   * Get files
   * @return files
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public V2IngressGatewaySpecAuthorizationExternalTlsFiles getFiles() {
    return files;
  }


  public void setFiles(V2IngressGatewaySpecAuthorizationExternalTlsFiles files) {
    this.files = files;
  }


  public V2IngressGatewaySpecAuthorizationExternalTls mode(ModeEnum mode) {
    
    this.mode = mode;
    return this;
  }

   /**
   * Get mode
   * @return mode
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public ModeEnum getMode() {
    return mode;
  }


  public void setMode(ModeEnum mode) {
    this.mode = mode;
  }


  public V2IngressGatewaySpecAuthorizationExternalTls subjectAltNames(List<String> subjectAltNames) {
    
    this.subjectAltNames = subjectAltNames;
    return this;
  }

  public V2IngressGatewaySpecAuthorizationExternalTls addSubjectAltNamesItem(String subjectAltNamesItem) {
    if (this.subjectAltNames == null) {
      this.subjectAltNames = new ArrayList<>();
    }
    this.subjectAltNames.add(subjectAltNamesItem);
    return this;
  }

   /**
   * Get subjectAltNames
   * @return subjectAltNames
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<String> getSubjectAltNames() {
    return subjectAltNames;
  }


  public void setSubjectAltNames(List<String> subjectAltNames) {
    this.subjectAltNames = subjectAltNames;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V2IngressGatewaySpecAuthorizationExternalTls v2IngressGatewaySpecAuthorizationExternalTls = (V2IngressGatewaySpecAuthorizationExternalTls) o;
    return Objects.equals(this.files, v2IngressGatewaySpecAuthorizationExternalTls.files) &&
        Objects.equals(this.mode, v2IngressGatewaySpecAuthorizationExternalTls.mode) &&
        Objects.equals(this.subjectAltNames, v2IngressGatewaySpecAuthorizationExternalTls.subjectAltNames);
  }

  @Override
  public int hashCode() {
    return Objects.hash(files, mode, subjectAltNames);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V2IngressGatewaySpecAuthorizationExternalTls {\n");
    sb.append("    files: ").append(toIndentedString(files)).append("\n");
    sb.append("    mode: ").append(toIndentedString(mode)).append("\n");
    sb.append("    subjectAltNames: ").append(toIndentedString(subjectAltNames)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

