/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.21.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.tetrate.tsb.gateway.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * Header manipulation rules to apply before returning a response to the caller.
 */
@ApiModel(description = "Header manipulation rules to apply before returning a response to the caller.")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-12-20T22:11:16.316Z[Etc/UTC]")
public class V2IngressGatewaySpecRoutingModifyHeadersResponse {
  public static final String SERIALIZED_NAME_ADD = "add";
  @SerializedName(SERIALIZED_NAME_ADD)
  private Map<String, String> add = null;

  public static final String SERIALIZED_NAME_REMOVE = "remove";
  @SerializedName(SERIALIZED_NAME_REMOVE)
  private List<String> remove = null;

  public static final String SERIALIZED_NAME_SET = "set";
  @SerializedName(SERIALIZED_NAME_SET)
  private Map<String, String> set = null;


  public V2IngressGatewaySpecRoutingModifyHeadersResponse add(Map<String, String> add) {
    
    this.add = add;
    return this;
  }

  public V2IngressGatewaySpecRoutingModifyHeadersResponse putAddItem(String key, String addItem) {
    if (this.add == null) {
      this.add = new HashMap<>();
    }
    this.add.put(key, addItem);
    return this;
  }

   /**
   * Get add
   * @return add
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Map<String, String> getAdd() {
    return add;
  }


  public void setAdd(Map<String, String> add) {
    this.add = add;
  }


  public V2IngressGatewaySpecRoutingModifyHeadersResponse remove(List<String> remove) {
    
    this.remove = remove;
    return this;
  }

  public V2IngressGatewaySpecRoutingModifyHeadersResponse addRemoveItem(String removeItem) {
    if (this.remove == null) {
      this.remove = new ArrayList<>();
    }
    this.remove.add(removeItem);
    return this;
  }

   /**
   * Remove a the specified headers.
   * @return remove
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Remove a the specified headers.")

  public List<String> getRemove() {
    return remove;
  }


  public void setRemove(List<String> remove) {
    this.remove = remove;
  }


  public V2IngressGatewaySpecRoutingModifyHeadersResponse set(Map<String, String> set) {
    
    this.set = set;
    return this;
  }

  public V2IngressGatewaySpecRoutingModifyHeadersResponse putSetItem(String key, String setItem) {
    if (this.set == null) {
      this.set = new HashMap<>();
    }
    this.set.put(key, setItem);
    return this;
  }

   /**
   * Overwrite the headers specified by key with the given values.
   * @return set
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Overwrite the headers specified by key with the given values.")

  public Map<String, String> getSet() {
    return set;
  }


  public void setSet(Map<String, String> set) {
    this.set = set;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V2IngressGatewaySpecRoutingModifyHeadersResponse v2IngressGatewaySpecRoutingModifyHeadersResponse = (V2IngressGatewaySpecRoutingModifyHeadersResponse) o;
    return Objects.equals(this.add, v2IngressGatewaySpecRoutingModifyHeadersResponse.add) &&
        Objects.equals(this.remove, v2IngressGatewaySpecRoutingModifyHeadersResponse.remove) &&
        Objects.equals(this.set, v2IngressGatewaySpecRoutingModifyHeadersResponse.set);
  }

  @Override
  public int hashCode() {
    return Objects.hash(add, remove, set);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V2IngressGatewaySpecRoutingModifyHeadersResponse {\n");
    sb.append("    add: ").append(toIndentedString(add)).append("\n");
    sb.append("    remove: ").append(toIndentedString(remove)).append("\n");
    sb.append("    set: ").append(toIndentedString(set)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

