/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.21.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.tetrate.tsb.gateway.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * Cross origin resource request policy settings for all routes.
 */
@ApiModel(description = "Cross origin resource request policy settings for all routes.")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-12-20T22:11:16.316Z[Etc/UTC]")
public class V2IngressGatewaySpecRoutingCorsPolicy {
  public static final String SERIALIZED_NAME_ALLOW_CREDENTIALS = "allowCredentials";
  @SerializedName(SERIALIZED_NAME_ALLOW_CREDENTIALS)
  private Object allowCredentials;

  public static final String SERIALIZED_NAME_ALLOW_HEADERS = "allowHeaders";
  @SerializedName(SERIALIZED_NAME_ALLOW_HEADERS)
  private List<String> allowHeaders = null;

  public static final String SERIALIZED_NAME_ALLOW_METHODS = "allowMethods";
  @SerializedName(SERIALIZED_NAME_ALLOW_METHODS)
  private List<String> allowMethods = null;

  public static final String SERIALIZED_NAME_ALLOW_ORIGIN = "allowOrigin";
  @SerializedName(SERIALIZED_NAME_ALLOW_ORIGIN)
  private List<String> allowOrigin = null;

  public static final String SERIALIZED_NAME_EXPOSE_HEADERS = "exposeHeaders";
  @SerializedName(SERIALIZED_NAME_EXPOSE_HEADERS)
  private List<String> exposeHeaders = null;

  public static final String SERIALIZED_NAME_MAX_AGE = "maxAge";
  @SerializedName(SERIALIZED_NAME_MAX_AGE)
  private String maxAge;


  public V2IngressGatewaySpecRoutingCorsPolicy allowCredentials(Object allowCredentials) {
    
    this.allowCredentials = allowCredentials;
    return this;
  }

   /**
   * Get allowCredentials
   * @return allowCredentials
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Object getAllowCredentials() {
    return allowCredentials;
  }


  public void setAllowCredentials(Object allowCredentials) {
    this.allowCredentials = allowCredentials;
  }


  public V2IngressGatewaySpecRoutingCorsPolicy allowHeaders(List<String> allowHeaders) {
    
    this.allowHeaders = allowHeaders;
    return this;
  }

  public V2IngressGatewaySpecRoutingCorsPolicy addAllowHeadersItem(String allowHeadersItem) {
    if (this.allowHeaders == null) {
      this.allowHeaders = new ArrayList<>();
    }
    this.allowHeaders.add(allowHeadersItem);
    return this;
  }

   /**
   * List of HTTP headers that can be used when requesting the resource.
   * @return allowHeaders
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "List of HTTP headers that can be used when requesting the resource.")

  public List<String> getAllowHeaders() {
    return allowHeaders;
  }


  public void setAllowHeaders(List<String> allowHeaders) {
    this.allowHeaders = allowHeaders;
  }


  public V2IngressGatewaySpecRoutingCorsPolicy allowMethods(List<String> allowMethods) {
    
    this.allowMethods = allowMethods;
    return this;
  }

  public V2IngressGatewaySpecRoutingCorsPolicy addAllowMethodsItem(String allowMethodsItem) {
    if (this.allowMethods == null) {
      this.allowMethods = new ArrayList<>();
    }
    this.allowMethods.add(allowMethodsItem);
    return this;
  }

   /**
   * List of HTTP methods allowed to access the resource.
   * @return allowMethods
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "List of HTTP methods allowed to access the resource.")

  public List<String> getAllowMethods() {
    return allowMethods;
  }


  public void setAllowMethods(List<String> allowMethods) {
    this.allowMethods = allowMethods;
  }


  public V2IngressGatewaySpecRoutingCorsPolicy allowOrigin(List<String> allowOrigin) {
    
    this.allowOrigin = allowOrigin;
    return this;
  }

  public V2IngressGatewaySpecRoutingCorsPolicy addAllowOriginItem(String allowOriginItem) {
    if (this.allowOrigin == null) {
      this.allowOrigin = new ArrayList<>();
    }
    this.allowOrigin.add(allowOriginItem);
    return this;
  }

   /**
   * The list of origins that are allowed to perform CORS requests.
   * @return allowOrigin
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The list of origins that are allowed to perform CORS requests.")

  public List<String> getAllowOrigin() {
    return allowOrigin;
  }


  public void setAllowOrigin(List<String> allowOrigin) {
    this.allowOrigin = allowOrigin;
  }


  public V2IngressGatewaySpecRoutingCorsPolicy exposeHeaders(List<String> exposeHeaders) {
    
    this.exposeHeaders = exposeHeaders;
    return this;
  }

  public V2IngressGatewaySpecRoutingCorsPolicy addExposeHeadersItem(String exposeHeadersItem) {
    if (this.exposeHeaders == null) {
      this.exposeHeaders = new ArrayList<>();
    }
    this.exposeHeaders.add(exposeHeadersItem);
    return this;
  }

   /**
   * A white list of HTTP headers that the browsers are allowed to access.
   * @return exposeHeaders
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "A white list of HTTP headers that the browsers are allowed to access.")

  public List<String> getExposeHeaders() {
    return exposeHeaders;
  }


  public void setExposeHeaders(List<String> exposeHeaders) {
    this.exposeHeaders = exposeHeaders;
  }


  public V2IngressGatewaySpecRoutingCorsPolicy maxAge(String maxAge) {
    
    this.maxAge = maxAge;
    return this;
  }

   /**
   * Specifies how long the results of a preflight request can be cached.
   * @return maxAge
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Specifies how long the results of a preflight request can be cached.")

  public String getMaxAge() {
    return maxAge;
  }


  public void setMaxAge(String maxAge) {
    this.maxAge = maxAge;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V2IngressGatewaySpecRoutingCorsPolicy v2IngressGatewaySpecRoutingCorsPolicy = (V2IngressGatewaySpecRoutingCorsPolicy) o;
    return Objects.equals(this.allowCredentials, v2IngressGatewaySpecRoutingCorsPolicy.allowCredentials) &&
        Objects.equals(this.allowHeaders, v2IngressGatewaySpecRoutingCorsPolicy.allowHeaders) &&
        Objects.equals(this.allowMethods, v2IngressGatewaySpecRoutingCorsPolicy.allowMethods) &&
        Objects.equals(this.allowOrigin, v2IngressGatewaySpecRoutingCorsPolicy.allowOrigin) &&
        Objects.equals(this.exposeHeaders, v2IngressGatewaySpecRoutingCorsPolicy.exposeHeaders) &&
        Objects.equals(this.maxAge, v2IngressGatewaySpecRoutingCorsPolicy.maxAge);
  }

  @Override
  public int hashCode() {
    return Objects.hash(allowCredentials, allowHeaders, allowMethods, allowOrigin, exposeHeaders, maxAge);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V2IngressGatewaySpecRoutingCorsPolicy {\n");
    sb.append("    allowCredentials: ").append(toIndentedString(allowCredentials)).append("\n");
    sb.append("    allowHeaders: ").append(toIndentedString(allowHeaders)).append("\n");
    sb.append("    allowMethods: ").append(toIndentedString(allowMethods)).append("\n");
    sb.append("    allowOrigin: ").append(toIndentedString(allowOrigin)).append("\n");
    sb.append("    exposeHeaders: ").append(toIndentedString(exposeHeaders)).append("\n");
    sb.append("    maxAge: ").append(toIndentedString(maxAge)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

