/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.21.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.tetrate.tsb.gateway.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.tetrate.tsb.gateway.models.V2IngressGatewaySpecRoutingMatch;
import io.tetrate.tsb.gateway.models.V2IngressGatewaySpecRoutingModify;
import io.tetrate.tsb.gateway.models.V2IngressGatewaySpecRoutingRedirect;
import io.tetrate.tsb.gateway.models.V2IngressGatewaySpecRoutingRoute;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * V2IngressGatewaySpecRoutingRules
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-12-20T22:11:16.316Z[Etc/UTC]")
public class V2IngressGatewaySpecRoutingRules {
  public static final String SERIALIZED_NAME_MATCH = "match";
  @SerializedName(SERIALIZED_NAME_MATCH)
  private List<V2IngressGatewaySpecRoutingMatch> match = null;

  public static final String SERIALIZED_NAME_MODIFY = "modify";
  @SerializedName(SERIALIZED_NAME_MODIFY)
  private V2IngressGatewaySpecRoutingModify modify;

  public static final String SERIALIZED_NAME_REDIRECT = "redirect";
  @SerializedName(SERIALIZED_NAME_REDIRECT)
  private V2IngressGatewaySpecRoutingRedirect redirect;

  public static final String SERIALIZED_NAME_ROUTE = "route";
  @SerializedName(SERIALIZED_NAME_ROUTE)
  private V2IngressGatewaySpecRoutingRoute route;


  public V2IngressGatewaySpecRoutingRules match(List<V2IngressGatewaySpecRoutingMatch> match) {
    
    this.match = match;
    return this;
  }

  public V2IngressGatewaySpecRoutingRules addMatchItem(V2IngressGatewaySpecRoutingMatch matchItem) {
    if (this.match == null) {
      this.match = new ArrayList<>();
    }
    this.match.add(matchItem);
    return this;
  }

   /**
   * One or more match conditions (OR-ed).
   * @return match
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "One or more match conditions (OR-ed).")

  public List<V2IngressGatewaySpecRoutingMatch> getMatch() {
    return match;
  }


  public void setMatch(List<V2IngressGatewaySpecRoutingMatch> match) {
    this.match = match;
  }


  public V2IngressGatewaySpecRoutingRules modify(V2IngressGatewaySpecRoutingModify modify) {
    
    this.modify = modify;
    return this;
  }

   /**
   * Get modify
   * @return modify
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public V2IngressGatewaySpecRoutingModify getModify() {
    return modify;
  }


  public void setModify(V2IngressGatewaySpecRoutingModify modify) {
    this.modify = modify;
  }


  public V2IngressGatewaySpecRoutingRules redirect(V2IngressGatewaySpecRoutingRedirect redirect) {
    
    this.redirect = redirect;
    return this;
  }

   /**
   * Get redirect
   * @return redirect
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public V2IngressGatewaySpecRoutingRedirect getRedirect() {
    return redirect;
  }


  public void setRedirect(V2IngressGatewaySpecRoutingRedirect redirect) {
    this.redirect = redirect;
  }


  public V2IngressGatewaySpecRoutingRules route(V2IngressGatewaySpecRoutingRoute route) {
    
    this.route = route;
    return this;
  }

   /**
   * Get route
   * @return route
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public V2IngressGatewaySpecRoutingRoute getRoute() {
    return route;
  }


  public void setRoute(V2IngressGatewaySpecRoutingRoute route) {
    this.route = route;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V2IngressGatewaySpecRoutingRules v2IngressGatewaySpecRoutingRules = (V2IngressGatewaySpecRoutingRules) o;
    return Objects.equals(this.match, v2IngressGatewaySpecRoutingRules.match) &&
        Objects.equals(this.modify, v2IngressGatewaySpecRoutingRules.modify) &&
        Objects.equals(this.redirect, v2IngressGatewaySpecRoutingRules.redirect) &&
        Objects.equals(this.route, v2IngressGatewaySpecRoutingRules.route);
  }

  @Override
  public int hashCode() {
    return Objects.hash(match, modify, redirect, route);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V2IngressGatewaySpecRoutingRules {\n");
    sb.append("    match: ").append(toIndentedString(match)).append("\n");
    sb.append("    modify: ").append(toIndentedString(modify)).append("\n");
    sb.append("    redirect: ").append(toIndentedString(redirect)).append("\n");
    sb.append("    route: ").append(toIndentedString(route)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

