/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.21.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.tetrate.tsb.gateway.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.tetrate.tsb.gateway.models.V2IngressGatewaySpecRateLimitingExternalService;
import io.tetrate.tsb.gateway.models.V2IngressGatewaySpecRateLimitingSettings;
import java.io.IOException;

/**
 * Configuration for rate limiting requests.
 */
@ApiModel(description = "Configuration for rate limiting requests.")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-12-20T22:11:16.316Z[Etc/UTC]")
public class V2IngressGatewaySpecRateLimiting {
  public static final String SERIALIZED_NAME_EXTERNAL_SERVICE = "externalService";
  @SerializedName(SERIALIZED_NAME_EXTERNAL_SERVICE)
  private V2IngressGatewaySpecRateLimitingExternalService externalService;

  public static final String SERIALIZED_NAME_SETTINGS = "settings";
  @SerializedName(SERIALIZED_NAME_SETTINGS)
  private V2IngressGatewaySpecRateLimitingSettings settings;


  public V2IngressGatewaySpecRateLimiting externalService(V2IngressGatewaySpecRateLimitingExternalService externalService) {
    
    this.externalService = externalService;
    return this;
  }

   /**
   * Get externalService
   * @return externalService
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public V2IngressGatewaySpecRateLimitingExternalService getExternalService() {
    return externalService;
  }


  public void setExternalService(V2IngressGatewaySpecRateLimitingExternalService externalService) {
    this.externalService = externalService;
  }


  public V2IngressGatewaySpecRateLimiting settings(V2IngressGatewaySpecRateLimitingSettings settings) {
    
    this.settings = settings;
    return this;
  }

   /**
   * Get settings
   * @return settings
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public V2IngressGatewaySpecRateLimitingSettings getSettings() {
    return settings;
  }


  public void setSettings(V2IngressGatewaySpecRateLimitingSettings settings) {
    this.settings = settings;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V2IngressGatewaySpecRateLimiting v2IngressGatewaySpecRateLimiting = (V2IngressGatewaySpecRateLimiting) o;
    return Objects.equals(this.externalService, v2IngressGatewaySpecRateLimiting.externalService) &&
        Objects.equals(this.settings, v2IngressGatewaySpecRateLimiting.settings);
  }

  @Override
  public int hashCode() {
    return Objects.hash(externalService, settings);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V2IngressGatewaySpecRateLimiting {\n");
    sb.append("    externalService: ").append(toIndentedString(externalService)).append("\n");
    sb.append("    settings: ").append(toIndentedString(settings)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

