/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.21.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.tetrate.tsb.gateway.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.tetrate.tsb.gateway.models.V2IngressGatewaySpecAuthorizationExternal;
import io.tetrate.tsb.gateway.models.V2IngressGatewaySpecAuthorizationLocal;
import java.io.IOException;

/**
 * Configuration to authorize a request.
 */
@ApiModel(description = "Configuration to authorize a request.")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-12-20T22:11:16.316Z[Etc/UTC]")
public class V2IngressGatewaySpecAuthorization {
  public static final String SERIALIZED_NAME_EXTERNAL = "external";
  @SerializedName(SERIALIZED_NAME_EXTERNAL)
  private V2IngressGatewaySpecAuthorizationExternal external;

  public static final String SERIALIZED_NAME_LOCAL = "local";
  @SerializedName(SERIALIZED_NAME_LOCAL)
  private V2IngressGatewaySpecAuthorizationLocal local;


  public V2IngressGatewaySpecAuthorization external(V2IngressGatewaySpecAuthorizationExternal external) {
    
    this.external = external;
    return this;
  }

   /**
   * Get external
   * @return external
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public V2IngressGatewaySpecAuthorizationExternal getExternal() {
    return external;
  }


  public void setExternal(V2IngressGatewaySpecAuthorizationExternal external) {
    this.external = external;
  }


  public V2IngressGatewaySpecAuthorization local(V2IngressGatewaySpecAuthorizationLocal local) {
    
    this.local = local;
    return this;
  }

   /**
   * Get local
   * @return local
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public V2IngressGatewaySpecAuthorizationLocal getLocal() {
    return local;
  }


  public void setLocal(V2IngressGatewaySpecAuthorizationLocal local) {
    this.local = local;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V2IngressGatewaySpecAuthorization v2IngressGatewaySpecAuthorization = (V2IngressGatewaySpecAuthorization) o;
    return Objects.equals(this.external, v2IngressGatewaySpecAuthorization.external) &&
        Objects.equals(this.local, v2IngressGatewaySpecAuthorization.local);
  }

  @Override
  public int hashCode() {
    return Objects.hash(external, local);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V2IngressGatewaySpecAuthorization {\n");
    sb.append("    external: ").append(toIndentedString(external)).append("\n");
    sb.append("    local: ").append(toIndentedString(local)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

