/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.21.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.tetrate.tsb.gateway.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.tetrate.tsb.gateway.models.V2IngressGatewaySpecRateLimitingExternalServiceDimensions;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * V2IngressGatewaySpecRateLimitingExternalServiceRules
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-12-20T22:11:16.316Z[Etc/UTC]")
public class V2IngressGatewaySpecRateLimitingExternalServiceRules {
  public static final String SERIALIZED_NAME_DIMENSIONS = "dimensions";
  @SerializedName(SERIALIZED_NAME_DIMENSIONS)
  private List<V2IngressGatewaySpecRateLimitingExternalServiceDimensions> dimensions = null;


  public V2IngressGatewaySpecRateLimitingExternalServiceRules dimensions(List<V2IngressGatewaySpecRateLimitingExternalServiceDimensions> dimensions) {
    
    this.dimensions = dimensions;
    return this;
  }

  public V2IngressGatewaySpecRateLimitingExternalServiceRules addDimensionsItem(V2IngressGatewaySpecRateLimitingExternalServiceDimensions dimensionsItem) {
    if (this.dimensions == null) {
      this.dimensions = new ArrayList<>();
    }
    this.dimensions.add(dimensionsItem);
    return this;
  }

   /**
   * A list of dimensions that are to be applied for this rate limit configuration.
   * @return dimensions
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "A list of dimensions that are to be applied for this rate limit configuration.")

  public List<V2IngressGatewaySpecRateLimitingExternalServiceDimensions> getDimensions() {
    return dimensions;
  }


  public void setDimensions(List<V2IngressGatewaySpecRateLimitingExternalServiceDimensions> dimensions) {
    this.dimensions = dimensions;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V2IngressGatewaySpecRateLimitingExternalServiceRules v2IngressGatewaySpecRateLimitingExternalServiceRules = (V2IngressGatewaySpecRateLimitingExternalServiceRules) o;
    return Objects.equals(this.dimensions, v2IngressGatewaySpecRateLimitingExternalServiceRules.dimensions);
  }

  @Override
  public int hashCode() {
    return Objects.hash(dimensions);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V2IngressGatewaySpecRateLimitingExternalServiceRules {\n");
    sb.append("    dimensions: ").append(toIndentedString(dimensions)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

