/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.21.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.tetrate.tsb.gateway.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.tetrate.tsb.gateway.models.V2IngressGatewaySpecAuthorizationExternalTls;
import io.tetrate.tsb.gateway.models.V2IngressGatewaySpecRateLimitingExternalServiceRules;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * Configure ratelimiting using an external ratelimit server.
 */
@ApiModel(description = "Configure ratelimiting using an external ratelimit server.")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-12-20T22:11:16.316Z[Etc/UTC]")
public class V2IngressGatewaySpecRateLimitingExternalService {
  public static final String SERIALIZED_NAME_DOMAIN = "domain";
  @SerializedName(SERIALIZED_NAME_DOMAIN)
  private String domain;

  public static final String SERIALIZED_NAME_FAIL_CLOSED = "failClosed";
  @SerializedName(SERIALIZED_NAME_FAIL_CLOSED)
  private Boolean failClosed;

  public static final String SERIALIZED_NAME_RATE_LIMIT_SERVER_URI = "rateLimitServerUri";
  @SerializedName(SERIALIZED_NAME_RATE_LIMIT_SERVER_URI)
  private String rateLimitServerUri;

  public static final String SERIALIZED_NAME_RULES = "rules";
  @SerializedName(SERIALIZED_NAME_RULES)
  private List<V2IngressGatewaySpecRateLimitingExternalServiceRules> rules = null;

  public static final String SERIALIZED_NAME_TIMEOUT = "timeout";
  @SerializedName(SERIALIZED_NAME_TIMEOUT)
  private String timeout;

  public static final String SERIALIZED_NAME_TLS = "tls";
  @SerializedName(SERIALIZED_NAME_TLS)
  private V2IngressGatewaySpecAuthorizationExternalTls tls;


  public V2IngressGatewaySpecRateLimitingExternalService domain(String domain) {
    
    this.domain = domain;
    return this;
  }

   /**
   * The rate limit domain to use when calling the rate limit service.
   * @return domain
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The rate limit domain to use when calling the rate limit service.")

  public String getDomain() {
    return domain;
  }


  public void setDomain(String domain) {
    this.domain = domain;
  }


  public V2IngressGatewaySpecRateLimitingExternalService failClosed(Boolean failClosed) {
    
    this.failClosed = failClosed;
    return this;
  }

   /**
   * Get failClosed
   * @return failClosed
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Boolean getFailClosed() {
    return failClosed;
  }


  public void setFailClosed(Boolean failClosed) {
    this.failClosed = failClosed;
  }


  public V2IngressGatewaySpecRateLimitingExternalService rateLimitServerUri(String rateLimitServerUri) {
    
    this.rateLimitServerUri = rateLimitServerUri;
    return this;
  }

   /**
   * The URI at which the external rate limit server can be reached.
   * @return rateLimitServerUri
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The URI at which the external rate limit server can be reached.")

  public String getRateLimitServerUri() {
    return rateLimitServerUri;
  }


  public void setRateLimitServerUri(String rateLimitServerUri) {
    this.rateLimitServerUri = rateLimitServerUri;
  }


  public V2IngressGatewaySpecRateLimitingExternalService rules(List<V2IngressGatewaySpecRateLimitingExternalServiceRules> rules) {
    
    this.rules = rules;
    return this;
  }

  public V2IngressGatewaySpecRateLimitingExternalService addRulesItem(V2IngressGatewaySpecRateLimitingExternalServiceRules rulesItem) {
    if (this.rules == null) {
      this.rules = new ArrayList<>();
    }
    this.rules.add(rulesItem);
    return this;
  }

   /**
   * A set of rate limit rules.
   * @return rules
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "A set of rate limit rules.")

  public List<V2IngressGatewaySpecRateLimitingExternalServiceRules> getRules() {
    return rules;
  }


  public void setRules(List<V2IngressGatewaySpecRateLimitingExternalServiceRules> rules) {
    this.rules = rules;
  }


  public V2IngressGatewaySpecRateLimitingExternalService timeout(String timeout) {
    
    this.timeout = timeout;
    return this;
  }

   /**
   * The timeout in seconds for the external rate limit server RPC.
   * @return timeout
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The timeout in seconds for the external rate limit server RPC.")

  public String getTimeout() {
    return timeout;
  }


  public void setTimeout(String timeout) {
    this.timeout = timeout;
  }


  public V2IngressGatewaySpecRateLimitingExternalService tls(V2IngressGatewaySpecAuthorizationExternalTls tls) {
    
    this.tls = tls;
    return this;
  }

   /**
   * Get tls
   * @return tls
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public V2IngressGatewaySpecAuthorizationExternalTls getTls() {
    return tls;
  }


  public void setTls(V2IngressGatewaySpecAuthorizationExternalTls tls) {
    this.tls = tls;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V2IngressGatewaySpecRateLimitingExternalService v2IngressGatewaySpecRateLimitingExternalService = (V2IngressGatewaySpecRateLimitingExternalService) o;
    return Objects.equals(this.domain, v2IngressGatewaySpecRateLimitingExternalService.domain) &&
        Objects.equals(this.failClosed, v2IngressGatewaySpecRateLimitingExternalService.failClosed) &&
        Objects.equals(this.rateLimitServerUri, v2IngressGatewaySpecRateLimitingExternalService.rateLimitServerUri) &&
        Objects.equals(this.rules, v2IngressGatewaySpecRateLimitingExternalService.rules) &&
        Objects.equals(this.timeout, v2IngressGatewaySpecRateLimitingExternalService.timeout) &&
        Objects.equals(this.tls, v2IngressGatewaySpecRateLimitingExternalService.tls);
  }

  @Override
  public int hashCode() {
    return Objects.hash(domain, failClosed, rateLimitServerUri, rules, timeout, tls);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V2IngressGatewaySpecRateLimitingExternalService {\n");
    sb.append("    domain: ").append(toIndentedString(domain)).append("\n");
    sb.append("    failClosed: ").append(toIndentedString(failClosed)).append("\n");
    sb.append("    rateLimitServerUri: ").append(toIndentedString(rateLimitServerUri)).append("\n");
    sb.append("    rules: ").append(toIndentedString(rules)).append("\n");
    sb.append("    timeout: ").append(toIndentedString(timeout)).append("\n");
    sb.append("    tls: ").append(toIndentedString(tls)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

