/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.21.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.tetrate.tsb.gateway.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.tetrate.tsb.gateway.models.V2IngressGatewaySpecRoutingModifyHeaders;
import io.tetrate.tsb.gateway.models.V2IngressGatewaySpecRoutingModifyRewrite;
import java.io.IOException;

/**
 * One or more mutations to be performed before forwarding.
 */
@ApiModel(description = "One or more mutations to be performed before forwarding.")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-12-20T22:11:16.316Z[Etc/UTC]")
public class V2IngressGatewaySpecRoutingModify {
  public static final String SERIALIZED_NAME_HEADERS = "headers";
  @SerializedName(SERIALIZED_NAME_HEADERS)
  private V2IngressGatewaySpecRoutingModifyHeaders headers;

  public static final String SERIALIZED_NAME_REWRITE = "rewrite";
  @SerializedName(SERIALIZED_NAME_REWRITE)
  private V2IngressGatewaySpecRoutingModifyRewrite rewrite;


  public V2IngressGatewaySpecRoutingModify headers(V2IngressGatewaySpecRoutingModifyHeaders headers) {
    
    this.headers = headers;
    return this;
  }

   /**
   * Get headers
   * @return headers
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public V2IngressGatewaySpecRoutingModifyHeaders getHeaders() {
    return headers;
  }


  public void setHeaders(V2IngressGatewaySpecRoutingModifyHeaders headers) {
    this.headers = headers;
  }


  public V2IngressGatewaySpecRoutingModify rewrite(V2IngressGatewaySpecRoutingModifyRewrite rewrite) {
    
    this.rewrite = rewrite;
    return this;
  }

   /**
   * Get rewrite
   * @return rewrite
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public V2IngressGatewaySpecRoutingModifyRewrite getRewrite() {
    return rewrite;
  }


  public void setRewrite(V2IngressGatewaySpecRoutingModifyRewrite rewrite) {
    this.rewrite = rewrite;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V2IngressGatewaySpecRoutingModify v2IngressGatewaySpecRoutingModify = (V2IngressGatewaySpecRoutingModify) o;
    return Objects.equals(this.headers, v2IngressGatewaySpecRoutingModify.headers) &&
        Objects.equals(this.rewrite, v2IngressGatewaySpecRoutingModify.rewrite);
  }

  @Override
  public int hashCode() {
    return Objects.hash(headers, rewrite);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V2IngressGatewaySpecRoutingModify {\n");
    sb.append("    headers: ").append(toIndentedString(headers)).append("\n");
    sb.append("    rewrite: ").append(toIndentedString(rewrite)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

