/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.21.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.tetrate.tsb.gateway.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * Redirect the request to a different host or URL or both.
 */
@ApiModel(description = "Redirect the request to a different host or URL or both.")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-12-20T22:11:16.316Z[Etc/UTC]")
public class V2IngressGatewaySpecRoutingRedirect {
  public static final String SERIALIZED_NAME_AUTHORITY = "authority";
  @SerializedName(SERIALIZED_NAME_AUTHORITY)
  private String authority;

  public static final String SERIALIZED_NAME_PORT = "port";
  @SerializedName(SERIALIZED_NAME_PORT)
  private Integer port;

  public static final String SERIALIZED_NAME_REDIRECT_CODE = "redirectCode";
  @SerializedName(SERIALIZED_NAME_REDIRECT_CODE)
  private Integer redirectCode;

  public static final String SERIALIZED_NAME_SCHEME = "scheme";
  @SerializedName(SERIALIZED_NAME_SCHEME)
  private String scheme;

  public static final String SERIALIZED_NAME_URI = "uri";
  @SerializedName(SERIALIZED_NAME_URI)
  private String uri;


  public V2IngressGatewaySpecRoutingRedirect authority(String authority) {
    
    this.authority = authority;
    return this;
  }

   /**
   * On a redirect, overwrite the Authority/Host portion of the URL with this value.
   * @return authority
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "On a redirect, overwrite the Authority/Host portion of the URL with this value.")

  public String getAuthority() {
    return authority;
  }


  public void setAuthority(String authority) {
    this.authority = authority;
  }


  public V2IngressGatewaySpecRoutingRedirect port(Integer port) {
    
    this.port = port;
    return this;
  }

   /**
   * Get port
   * minimum: 0
   * maximum: 4294967295
   * @return port
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Integer getPort() {
    return port;
  }


  public void setPort(Integer port) {
    this.port = port;
  }


  public V2IngressGatewaySpecRoutingRedirect redirectCode(Integer redirectCode) {
    
    this.redirectCode = redirectCode;
    return this;
  }

   /**
   * Get redirectCode
   * minimum: 0
   * maximum: 4294967295
   * @return redirectCode
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Integer getRedirectCode() {
    return redirectCode;
  }


  public void setRedirectCode(Integer redirectCode) {
    this.redirectCode = redirectCode;
  }


  public V2IngressGatewaySpecRoutingRedirect scheme(String scheme) {
    
    this.scheme = scheme;
    return this;
  }

   /**
   * On a redirect, overwrite the scheme with this one.
   * @return scheme
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "On a redirect, overwrite the scheme with this one.")

  public String getScheme() {
    return scheme;
  }


  public void setScheme(String scheme) {
    this.scheme = scheme;
  }


  public V2IngressGatewaySpecRoutingRedirect uri(String uri) {
    
    this.uri = uri;
    return this;
  }

   /**
   * On a redirect, overwrite the Path portion of the URL with this value.
   * @return uri
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "On a redirect, overwrite the Path portion of the URL with this value.")

  public String getUri() {
    return uri;
  }


  public void setUri(String uri) {
    this.uri = uri;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V2IngressGatewaySpecRoutingRedirect v2IngressGatewaySpecRoutingRedirect = (V2IngressGatewaySpecRoutingRedirect) o;
    return Objects.equals(this.authority, v2IngressGatewaySpecRoutingRedirect.authority) &&
        Objects.equals(this.port, v2IngressGatewaySpecRoutingRedirect.port) &&
        Objects.equals(this.redirectCode, v2IngressGatewaySpecRoutingRedirect.redirectCode) &&
        Objects.equals(this.scheme, v2IngressGatewaySpecRoutingRedirect.scheme) &&
        Objects.equals(this.uri, v2IngressGatewaySpecRoutingRedirect.uri);
  }

  @Override
  public int hashCode() {
    return Objects.hash(authority, port, redirectCode, scheme, uri);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V2IngressGatewaySpecRoutingRedirect {\n");
    sb.append("    authority: ").append(toIndentedString(authority)).append("\n");
    sb.append("    port: ").append(toIndentedString(port)).append("\n");
    sb.append("    redirectCode: ").append(toIndentedString(redirectCode)).append("\n");
    sb.append("    scheme: ").append(toIndentedString(scheme)).append("\n");
    sb.append("    uri: ").append(toIndentedString(uri)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

