/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.21.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.tetrate.tsb.gateway.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.tetrate.tsb.gateway.models.V2IngressGatewaySpecRateLimitingExternalServiceHeaderValueMatchHeaders;
import io.tetrate.tsb.gateway.models.V2IngressGatewaySpecRoutingUri;
import java.io.IOException;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * V2IngressGatewaySpecRoutingMatch
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-12-20T22:11:16.316Z[Etc/UTC]")
public class V2IngressGatewaySpecRoutingMatch {
  public static final String SERIALIZED_NAME_HEADERS = "headers";
  @SerializedName(SERIALIZED_NAME_HEADERS)
  private Map<String, V2IngressGatewaySpecRateLimitingExternalServiceHeaderValueMatchHeaders> headers = null;

  public static final String SERIALIZED_NAME_URI = "uri";
  @SerializedName(SERIALIZED_NAME_URI)
  private V2IngressGatewaySpecRoutingUri uri;


  public V2IngressGatewaySpecRoutingMatch headers(Map<String, V2IngressGatewaySpecRateLimitingExternalServiceHeaderValueMatchHeaders> headers) {
    
    this.headers = headers;
    return this;
  }

  public V2IngressGatewaySpecRoutingMatch putHeadersItem(String key, V2IngressGatewaySpecRateLimitingExternalServiceHeaderValueMatchHeaders headersItem) {
    if (this.headers == null) {
      this.headers = new HashMap<>();
    }
    this.headers.put(key, headersItem);
    return this;
  }

   /**
   * The header keys must be lowercase and use hyphen as the separator, e.g.
   * @return headers
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The header keys must be lowercase and use hyphen as the separator, e.g.")

  public Map<String, V2IngressGatewaySpecRateLimitingExternalServiceHeaderValueMatchHeaders> getHeaders() {
    return headers;
  }


  public void setHeaders(Map<String, V2IngressGatewaySpecRateLimitingExternalServiceHeaderValueMatchHeaders> headers) {
    this.headers = headers;
  }


  public V2IngressGatewaySpecRoutingMatch uri(V2IngressGatewaySpecRoutingUri uri) {
    
    this.uri = uri;
    return this;
  }

   /**
   * Get uri
   * @return uri
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public V2IngressGatewaySpecRoutingUri getUri() {
    return uri;
  }


  public void setUri(V2IngressGatewaySpecRoutingUri uri) {
    this.uri = uri;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V2IngressGatewaySpecRoutingMatch v2IngressGatewaySpecRoutingMatch = (V2IngressGatewaySpecRoutingMatch) o;
    return Objects.equals(this.headers, v2IngressGatewaySpecRoutingMatch.headers) &&
        Objects.equals(this.uri, v2IngressGatewaySpecRoutingMatch.uri);
  }

  @Override
  public int hashCode() {
    return Objects.hash(headers, uri);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V2IngressGatewaySpecRoutingMatch {\n");
    sb.append("    headers: ").append(toIndentedString(headers)).append("\n");
    sb.append("    uri: ").append(toIndentedString(uri)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

