/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.21.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.tetrate.tsb.gateway.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * V2IngressGatewaySpecAuthorizationLocalTo
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-12-20T22:11:16.316Z[Etc/UTC]")
public class V2IngressGatewaySpecAuthorizationLocalTo {
  public static final String SERIALIZED_NAME_METHODS = "methods";
  @SerializedName(SERIALIZED_NAME_METHODS)
  private List<String> methods = null;

  public static final String SERIALIZED_NAME_PATHS = "paths";
  @SerializedName(SERIALIZED_NAME_PATHS)
  private List<String> paths = null;


  public V2IngressGatewaySpecAuthorizationLocalTo methods(List<String> methods) {
    
    this.methods = methods;
    return this;
  }

  public V2IngressGatewaySpecAuthorizationLocalTo addMethodsItem(String methodsItem) {
    if (this.methods == null) {
      this.methods = new ArrayList<>();
    }
    this.methods.add(methodsItem);
    return this;
  }

   /**
   * The HTTP methods that are allowed by this rule.
   * @return methods
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The HTTP methods that are allowed by this rule.")

  public List<String> getMethods() {
    return methods;
  }


  public void setMethods(List<String> methods) {
    this.methods = methods;
  }


  public V2IngressGatewaySpecAuthorizationLocalTo paths(List<String> paths) {
    
    this.paths = paths;
    return this;
  }

  public V2IngressGatewaySpecAuthorizationLocalTo addPathsItem(String pathsItem) {
    if (this.paths == null) {
      this.paths = new ArrayList<>();
    }
    this.paths.add(pathsItem);
    return this;
  }

   /**
   * The request path where the request is made against.
   * @return paths
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The request path where the request is made against.")

  public List<String> getPaths() {
    return paths;
  }


  public void setPaths(List<String> paths) {
    this.paths = paths;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V2IngressGatewaySpecAuthorizationLocalTo v2IngressGatewaySpecAuthorizationLocalTo = (V2IngressGatewaySpecAuthorizationLocalTo) o;
    return Objects.equals(this.methods, v2IngressGatewaySpecAuthorizationLocalTo.methods) &&
        Objects.equals(this.paths, v2IngressGatewaySpecAuthorizationLocalTo.paths);
  }

  @Override
  public int hashCode() {
    return Objects.hash(methods, paths);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V2IngressGatewaySpecAuthorizationLocalTo {\n");
    sb.append("    methods: ").append(toIndentedString(methods)).append("\n");
    sb.append("    paths: ").append(toIndentedString(paths)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

