/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.21.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.tetrate.tsb.gateway.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.tetrate.tsb.gateway.models.V2IngressGatewaySpecRateLimitingSettingsHeader;
import io.tetrate.tsb.gateway.models.V2IngressGatewaySpecRateLimitingSettingsRemoteAddress;
import java.io.IOException;

/**
 * V2IngressGatewaySpecRateLimitingSettingsDimensions
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-12-20T22:11:16.316Z[Etc/UTC]")
public class V2IngressGatewaySpecRateLimitingSettingsDimensions {
  public static final String SERIALIZED_NAME_HEADER = "header";
  @SerializedName(SERIALIZED_NAME_HEADER)
  private V2IngressGatewaySpecRateLimitingSettingsHeader header;

  public static final String SERIALIZED_NAME_REMOTE_ADDRESS = "remoteAddress";
  @SerializedName(SERIALIZED_NAME_REMOTE_ADDRESS)
  private V2IngressGatewaySpecRateLimitingSettingsRemoteAddress remoteAddress;


  public V2IngressGatewaySpecRateLimitingSettingsDimensions header(V2IngressGatewaySpecRateLimitingSettingsHeader header) {
    
    this.header = header;
    return this;
  }

   /**
   * Get header
   * @return header
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public V2IngressGatewaySpecRateLimitingSettingsHeader getHeader() {
    return header;
  }


  public void setHeader(V2IngressGatewaySpecRateLimitingSettingsHeader header) {
    this.header = header;
  }


  public V2IngressGatewaySpecRateLimitingSettingsDimensions remoteAddress(V2IngressGatewaySpecRateLimitingSettingsRemoteAddress remoteAddress) {
    
    this.remoteAddress = remoteAddress;
    return this;
  }

   /**
   * Get remoteAddress
   * @return remoteAddress
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public V2IngressGatewaySpecRateLimitingSettingsRemoteAddress getRemoteAddress() {
    return remoteAddress;
  }


  public void setRemoteAddress(V2IngressGatewaySpecRateLimitingSettingsRemoteAddress remoteAddress) {
    this.remoteAddress = remoteAddress;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V2IngressGatewaySpecRateLimitingSettingsDimensions v2IngressGatewaySpecRateLimitingSettingsDimensions = (V2IngressGatewaySpecRateLimitingSettingsDimensions) o;
    return Objects.equals(this.header, v2IngressGatewaySpecRateLimitingSettingsDimensions.header) &&
        Objects.equals(this.remoteAddress, v2IngressGatewaySpecRateLimitingSettingsDimensions.remoteAddress);
  }

  @Override
  public int hashCode() {
    return Objects.hash(header, remoteAddress);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V2IngressGatewaySpecRateLimitingSettingsDimensions {\n");
    sb.append("    header: ").append(toIndentedString(header)).append("\n");
    sb.append("    remoteAddress: ").append(toIndentedString(remoteAddress)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

