/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.21.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.tetrate.tsb.gateway.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.tetrate.tsb.gateway.models.V2IngressGatewaySpecAuthorizationExternalTls;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * V2IngressGatewaySpecAuthorizationExternal
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-12-20T22:11:16.316Z[Etc/UTC]")
public class V2IngressGatewaySpecAuthorizationExternal {
  public static final String SERIALIZED_NAME_INCLUDE_REQUEST_HEADERS = "includeRequestHeaders";
  @SerializedName(SERIALIZED_NAME_INCLUDE_REQUEST_HEADERS)
  private List<String> includeRequestHeaders = null;

  public static final String SERIALIZED_NAME_TLS = "tls";
  @SerializedName(SERIALIZED_NAME_TLS)
  private V2IngressGatewaySpecAuthorizationExternalTls tls;

  public static final String SERIALIZED_NAME_URI = "uri";
  @SerializedName(SERIALIZED_NAME_URI)
  private String uri;


  public V2IngressGatewaySpecAuthorizationExternal includeRequestHeaders(List<String> includeRequestHeaders) {
    
    this.includeRequestHeaders = includeRequestHeaders;
    return this;
  }

  public V2IngressGatewaySpecAuthorizationExternal addIncludeRequestHeadersItem(String includeRequestHeadersItem) {
    if (this.includeRequestHeaders == null) {
      this.includeRequestHeaders = new ArrayList<>();
    }
    this.includeRequestHeaders.add(includeRequestHeadersItem);
    return this;
  }

   /**
   * Get includeRequestHeaders
   * @return includeRequestHeaders
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<String> getIncludeRequestHeaders() {
    return includeRequestHeaders;
  }


  public void setIncludeRequestHeaders(List<String> includeRequestHeaders) {
    this.includeRequestHeaders = includeRequestHeaders;
  }


  public V2IngressGatewaySpecAuthorizationExternal tls(V2IngressGatewaySpecAuthorizationExternalTls tls) {
    
    this.tls = tls;
    return this;
  }

   /**
   * Get tls
   * @return tls
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public V2IngressGatewaySpecAuthorizationExternalTls getTls() {
    return tls;
  }


  public void setTls(V2IngressGatewaySpecAuthorizationExternalTls tls) {
    this.tls = tls;
  }


  public V2IngressGatewaySpecAuthorizationExternal uri(String uri) {
    
    this.uri = uri;
    return this;
  }

   /**
   * Get uri
   * @return uri
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getUri() {
    return uri;
  }


  public void setUri(String uri) {
    this.uri = uri;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V2IngressGatewaySpecAuthorizationExternal v2IngressGatewaySpecAuthorizationExternal = (V2IngressGatewaySpecAuthorizationExternal) o;
    return Objects.equals(this.includeRequestHeaders, v2IngressGatewaySpecAuthorizationExternal.includeRequestHeaders) &&
        Objects.equals(this.tls, v2IngressGatewaySpecAuthorizationExternal.tls) &&
        Objects.equals(this.uri, v2IngressGatewaySpecAuthorizationExternal.uri);
  }

  @Override
  public int hashCode() {
    return Objects.hash(includeRequestHeaders, tls, uri);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V2IngressGatewaySpecAuthorizationExternal {\n");
    sb.append("    includeRequestHeaders: ").append(toIndentedString(includeRequestHeaders)).append("\n");
    sb.append("    tls: ").append(toIndentedString(tls)).append("\n");
    sb.append("    uri: ").append(toIndentedString(uri)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

