/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.21.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.tetrate.tsb.gateway.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * Rate limit on the value of certain request headers.
 */
@ApiModel(description = "Rate limit on the value of certain request headers.")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-12-20T22:11:16.316Z[Etc/UTC]")
public class V2IngressGatewaySpecRateLimitingExternalServiceRequestHeaders {
  public static final String SERIALIZED_NAME_DESCRIPTOR_KEY = "descriptorKey";
  @SerializedName(SERIALIZED_NAME_DESCRIPTOR_KEY)
  private String descriptorKey;

  public static final String SERIALIZED_NAME_HEADER_NAME = "headerName";
  @SerializedName(SERIALIZED_NAME_HEADER_NAME)
  private String headerName;


  public V2IngressGatewaySpecRateLimitingExternalServiceRequestHeaders descriptorKey(String descriptorKey) {
    
    this.descriptorKey = descriptorKey;
    return this;
  }

   /**
   * The key to use in the descriptor entry.
   * @return descriptorKey
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The key to use in the descriptor entry.")

  public String getDescriptorKey() {
    return descriptorKey;
  }


  public void setDescriptorKey(String descriptorKey) {
    this.descriptorKey = descriptorKey;
  }


  public V2IngressGatewaySpecRateLimitingExternalServiceRequestHeaders headerName(String headerName) {
    
    this.headerName = headerName;
    return this;
  }

   /**
   * The header name to be queried from the request headers.
   * @return headerName
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The header name to be queried from the request headers.")

  public String getHeaderName() {
    return headerName;
  }


  public void setHeaderName(String headerName) {
    this.headerName = headerName;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V2IngressGatewaySpecRateLimitingExternalServiceRequestHeaders v2IngressGatewaySpecRateLimitingExternalServiceRequestHeaders = (V2IngressGatewaySpecRateLimitingExternalServiceRequestHeaders) o;
    return Objects.equals(this.descriptorKey, v2IngressGatewaySpecRateLimitingExternalServiceRequestHeaders.descriptorKey) &&
        Objects.equals(this.headerName, v2IngressGatewaySpecRateLimitingExternalServiceRequestHeaders.headerName);
  }

  @Override
  public int hashCode() {
    return Objects.hash(descriptorKey, headerName);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V2IngressGatewaySpecRateLimitingExternalServiceRequestHeaders {\n");
    sb.append("    descriptorKey: ").append(toIndentedString(descriptorKey)).append("\n");
    sb.append("    headerName: ").append(toIndentedString(headerName)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

