/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.21.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.tetrate.tsb.gateway.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.tetrate.tsb.gateway.models.V2IngressGatewaySpecRateLimitingSettingsDimensions;
import io.tetrate.tsb.gateway.models.V2IngressGatewaySpecRateLimitingSettingsLimit;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * V2IngressGatewaySpecRateLimitingSettingsRules
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-12-20T22:11:16.316Z[Etc/UTC]")
public class V2IngressGatewaySpecRateLimitingSettingsRules {
  public static final String SERIALIZED_NAME_DIMENSIONS = "dimensions";
  @SerializedName(SERIALIZED_NAME_DIMENSIONS)
  private List<V2IngressGatewaySpecRateLimitingSettingsDimensions> dimensions = null;

  public static final String SERIALIZED_NAME_LIMIT = "limit";
  @SerializedName(SERIALIZED_NAME_LIMIT)
  private V2IngressGatewaySpecRateLimitingSettingsLimit limit;


  public V2IngressGatewaySpecRateLimitingSettingsRules dimensions(List<V2IngressGatewaySpecRateLimitingSettingsDimensions> dimensions) {
    
    this.dimensions = dimensions;
    return this;
  }

  public V2IngressGatewaySpecRateLimitingSettingsRules addDimensionsItem(V2IngressGatewaySpecRateLimitingSettingsDimensions dimensionsItem) {
    if (this.dimensions == null) {
      this.dimensions = new ArrayList<>();
    }
    this.dimensions.add(dimensionsItem);
    return this;
  }

   /**
   * A list of dimensions to define each ratelimit rule.
   * @return dimensions
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "A list of dimensions to define each ratelimit rule.")

  public List<V2IngressGatewaySpecRateLimitingSettingsDimensions> getDimensions() {
    return dimensions;
  }


  public void setDimensions(List<V2IngressGatewaySpecRateLimitingSettingsDimensions> dimensions) {
    this.dimensions = dimensions;
  }


  public V2IngressGatewaySpecRateLimitingSettingsRules limit(V2IngressGatewaySpecRateLimitingSettingsLimit limit) {
    
    this.limit = limit;
    return this;
  }

   /**
   * Get limit
   * @return limit
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public V2IngressGatewaySpecRateLimitingSettingsLimit getLimit() {
    return limit;
  }


  public void setLimit(V2IngressGatewaySpecRateLimitingSettingsLimit limit) {
    this.limit = limit;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V2IngressGatewaySpecRateLimitingSettingsRules v2IngressGatewaySpecRateLimitingSettingsRules = (V2IngressGatewaySpecRateLimitingSettingsRules) o;
    return Objects.equals(this.dimensions, v2IngressGatewaySpecRateLimitingSettingsRules.dimensions) &&
        Objects.equals(this.limit, v2IngressGatewaySpecRateLimitingSettingsRules.limit);
  }

  @Override
  public int hashCode() {
    return Objects.hash(dimensions, limit);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V2IngressGatewaySpecRateLimitingSettingsRules {\n");
    sb.append("    dimensions: ").append(toIndentedString(dimensions)).append("\n");
    sb.append("    limit: ").append(toIndentedString(limit)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

