/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.21.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.tetrate.tsb.gateway.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * The ratelimit value that will be configured for the above rules.
 */
@ApiModel(description = "The ratelimit value that will be configured for the above rules.")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-12-20T22:11:16.316Z[Etc/UTC]")
public class V2IngressGatewaySpecRateLimitingSettingsLimit {
  public static final String SERIALIZED_NAME_REQUESTS_PER_UNIT = "requestsPerUnit";
  @SerializedName(SERIALIZED_NAME_REQUESTS_PER_UNIT)
  private Integer requestsPerUnit;

  /**
   * Specifies the unit of time for rate limit.
   */
  @JsonAdapter(UnitEnum.Adapter.class)
  public enum UnitEnum {
    UNKNOWN("UNKNOWN"),
    
    SECOND("SECOND"),
    
    MINUTE("MINUTE"),
    
    HOUR("HOUR"),
    
    DAY("DAY");

    private String value;

    UnitEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static UnitEnum fromValue(String value) {
      for (UnitEnum b : UnitEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<UnitEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final UnitEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public UnitEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return UnitEnum.fromValue(value);
      }
    }
  }

  public static final String SERIALIZED_NAME_UNIT = "unit";
  @SerializedName(SERIALIZED_NAME_UNIT)
  private UnitEnum unit;


  public V2IngressGatewaySpecRateLimitingSettingsLimit requestsPerUnit(Integer requestsPerUnit) {
    
    this.requestsPerUnit = requestsPerUnit;
    return this;
  }

   /**
   * Specifies the value of the rate limit.
   * minimum: 0
   * maximum: 4294967295
   * @return requestsPerUnit
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Specifies the value of the rate limit.")

  public Integer getRequestsPerUnit() {
    return requestsPerUnit;
  }


  public void setRequestsPerUnit(Integer requestsPerUnit) {
    this.requestsPerUnit = requestsPerUnit;
  }


  public V2IngressGatewaySpecRateLimitingSettingsLimit unit(UnitEnum unit) {
    
    this.unit = unit;
    return this;
  }

   /**
   * Specifies the unit of time for rate limit.
   * @return unit
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Specifies the unit of time for rate limit.")

  public UnitEnum getUnit() {
    return unit;
  }


  public void setUnit(UnitEnum unit) {
    this.unit = unit;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V2IngressGatewaySpecRateLimitingSettingsLimit v2IngressGatewaySpecRateLimitingSettingsLimit = (V2IngressGatewaySpecRateLimitingSettingsLimit) o;
    return Objects.equals(this.requestsPerUnit, v2IngressGatewaySpecRateLimitingSettingsLimit.requestsPerUnit) &&
        Objects.equals(this.unit, v2IngressGatewaySpecRateLimitingSettingsLimit.unit);
  }

  @Override
  public int hashCode() {
    return Objects.hash(requestsPerUnit, unit);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V2IngressGatewaySpecRateLimitingSettingsLimit {\n");
    sb.append("    requestsPerUnit: ").append(toIndentedString(requestsPerUnit)).append("\n");
    sb.append("    unit: ").append(toIndentedString(unit)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

